Task 11 &12
Iadolphe007/AirBnB_clone_v3 pull request #4
Opened 2023-10-29 18:23 UTC by Iadolphe007

Review and merge

2023-10-29 18:47 UTC, joekariuki3 requested changes
kindly check on the two issues.

2023-10-29 18:47 UTC, joekariuki3 commented on api/v1/views/places_reviews.py
> +    revire = Review(**data)
this should be  review, not revire

2023-10-29 18:47 UTC, joekariuki3 commented on api/v1/views/places_reviews.py
> +    reviews = [review.to_dict() for review in place.reviews)
reviews should be a list... check the closing bracket you used ) instead of ]

2023-10-30 07:04 UTC, Iadolphe007 commented
all issues fixed review again

2023-10-30 07:42 UTC, joekariuki3 approved these changes

2023-10-30 07:42 UTC, merged